### ISSUE TITLE
Question: filters under "Environment" in skipper?

### ISSUE THREAD

**Issue by petterjohansson** [ARCAD-Software/elias-vscode#1]
Is there a way to add filters for what versions you want to view in vscode skipper?

**Comment by sebjulliand** [comment]
Hi! Not with the current version!
What would be the attributes you'd like to filter on?

**Comment by petterjohansson** [comment]
Mostly the same things as in RDI. Not to differenciate between opened and integrated versions and have a filter where you could select the versions you want to to have in your view/filter. We have alot of versions, each developer could have 2-10 personal versions and without a filter it could be a struggle to find what you are looking for. 👍

**Comment by sebjulliand** [comment]
OK got it; it's more like having a "Favorite versions" node.
