### ISSUE TITLE
Error: connect ECONNREFUSED IP:2012

### ISSUE THREAD

**Issue by sgonchigar** [ARCAD-Software/elias-vscode#11]
Hello, getting below error. how to go about troubshooting.

[1/16/2024 1:53:06 PM] [INF] Activating ARCAD Elias
[1/16/2024 1:53:06 PM] [INF] Starting standalone mode
[1/16/2024 1:53:30 PM] [ERR] Failed to reach Elias ping /ping
[1/16/2024 1:53:30 PM] [ERR] Error: connect ECONNREFUSED ip:2012
[1/16/2024 1:53:30 PM] [ERR] Can't ping https://ip:2012/elias/arcad/v1

**Comment by sebjulliand** [comment]
Hi!
It seems like the Elias Rest API server has not been installed and/or is not running.
Please check the online documentation about the prerequisites: https://arcad-software.github.io/elias-vscode/#/pages/prerequisites
Then have a look at the setup section: https://arcad-software.github.io/elias-vscode/#/pages/setup

You can also checkout the Get Started walkthrough in VSCode:
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/78dabfb3-9850-473f-8ffc-be42aaf7123d)
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/a64f2a9c-385f-4754-9333-04b2d1862737)

In case you have issues setting up the Elias Rest API server, reach out to ARCAD customer support for further assistance.
