### ISSUE TITLE
RFE: distinguish between integrated and retrieved components

### ISSUE THREAD

**Issue by mlstoppa** [ARCAD-Software/elias-vscode#12]
Hi Sèbastien,

Is it possible to somehow distinguish when a component of an already integrated version has been retrieved from TEST?
Let's say a version contains a lot of components and only a few were retrieved to fix some bugs that had happened during the test session, how can I recognize the changed ones to transfer to test only those instead of integrate again the whole version? In some environments, those who do the integration are not the developers themselves.
Not even the tooltip says anything about it.

![image](https://github.com/ARCAD-Software/elias-vscode/assets/11289821/19d27835-6af3-4a78-8a4d-6784b6f6ddeb)

Thank you

**Comment by sebjulliand** [comment]
Noted.
For the moment, v2 will show the current environment in the tooltip.
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/716e1c61-4fb1-4946-b819-94b60735faa0)

But I'll think about a visual aid (or changing the icons altogether...).

**Comment by sebjulliand** [comment]
Ciao @mlstoppa !
Here is what I suggest:
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/3bd8950e-bca3-47ce-8892-95fceb60ca77)

- Blue: OK (component is compiled if compilable)
- Yellow: Component is OK and in test environment
- Red: component is compilable but not compiled

Since integrated version a yellow as well, that can let you see at a glance what is in test and what is not.

What do you think?

**Comment by mlstoppa** [comment]
> Noted. For the moment, v2 will show the current environment in the tooltip. ![image](https://private-user-images.githubusercontent.com/11096890/302649645-716e1c61-4fb1-4946-b819-94b60735faa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjc2OTcsIm5iZiI6MTcwNzMyNzM5NywicGF0aCI6Ii8xMTA5Njg5MC8zMDI2NDk2NDUtNzE2ZTFjNjEtNGZiMS00OTQ2LWI4MTktOTRiNjA3MzVmYWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE3MzYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YzRkNWM5ZWM0ZDVkMDc5NTRiNzBiMjhmNzIwMmM5NWIxYzNmYmEyNDliNTJlOWEwYzJlZDZhMDFkMTI2MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PhisDbXPEfFb6nECZ6yQ8o5J4z_FqP3xqlBCQVYw5os)
> 
> But I'll think about a visual aid (or changing the icons altogether...).

Ok, though I cannot see that attribute, right?
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11289821/84b9dc00-2457-419c-b646-8ec64b60f3b0)

**Comment by mlstoppa** [comment]
> Ciao @mlstoppa ! Here is what I suggest: ![image](https://private-user-images.githubusercontent.com/11096890/303033758-3bd8950e-bca3-47ce-8892-95fceb60ca77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjc4NTMsIm5iZiI6MTcwNzMyNzU1MywicGF0aCI6Ii8xMTA5Njg5MC8zMDMwMzM3NTgtM2JkODk1MGUtYmNhMy00N2NlLTg4OTItOTVmY2ViNjBjYTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE3MzkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YmU0MDQ1MGYxYjhmZTY0YjkxNThjM2RiZTBjNTc4ZjQ5NWUwNjEzNjE2MGExM2I2NWU0Nzk2OGMxOWU2MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.21dgQRIyfmz1wb3hWFT5sL6Bnrr4SDGM5FjEWknXWbk)
> 
> * Blue: OK (component is compiled if compilable)
> * Yellow: Component is OK and in test environment
> * Red: component is compilable but not compiled
> 
> Since integrated version a yellow as well, that can let you see at a glance what is in test and what is not.
> 
> What do you think?

The idea of using the yellow color for integrated objects is great, I am just wondering how these colors will be in an open version: just red and blue as it is now and with the same meaning they have in an integrated version, right?

**Comment by sebjulliand** [comment]
Exactly, yes; blue/red/yellow will always have the same meaning, disregarding the version status.
After a version integration, everything will be yellow (everything that can be transferred, that is); so if anything is blue or red in an integrated version, it means it's not in a test environment anymore.
