### ISSUE TITLE
Losing focus while editing source

### ISSUE THREAD

**Issue by petterjohansson** [ARCAD-Software/elias-vscode#15]
Hi!

Sometimes (of unknown reasons) ARCAD-Observer error message claims fokus from the editor window.
![image](https://github.com/ARCAD-Software/elias-vscode/assets/12429224/eff4bfad-29cb-4c9f-b4ae-3549a5976526)
It's kind of anoying when you type and suddently need to use the mouse to gain focus in the editor again.

Any date for the next large elias plugin update?

BR.
Petter

**Comment by sebjulliand** [comment]
@petterjohansson this error will be fixed in the upcoming v2 version, so it will be less anoying (the output view catches focus when an error occurred, but this error, due to a bug, occurred way too often).

The v2 should be out this week.

**Comment by sebjulliand** [comment]
Elias v2.1 is out!
https://github.com/ARCAD-Software/elias-vscode/releases/tag/2.1.0

**Comment by petterjohansson** [comment]
@sebjulliand  this thing have started to happen again - the output view catches the focus. Using v2.3.5 😄  
BR,
Petter

**Comment by sebjulliand** [comment]
Hi @petterjohansson ,
if you have a little gif or mpg of this happening, I'd be curious. Thanks.
