### ISSUE TITLE
RFE: Ordering versions by name descending

### ISSUE THREAD

**Issue by mlstoppa** [ARCAD-Software/elias-vscode#16]
Hi,
Is there a way to list versions ordered by name descending as it is with RDi?
This way, finding more recent versions would be easily done, especially in case of multiple versions listed among favourites and opened. 
Thank you

**Comment by sebjulliand** [comment]
There is no way as of now, but that will make for a nice enhancement!

**Comment by sebjulliand** [comment]
That will be added in Elias v2.1:
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/03589636-8bf5-4356-8b61-fffac08a1be4)

The `Sort` action will be added on several nodes to allowing to sort their content alphabetically (ascending and descending).

**Comment by mlstoppa** [comment]
Hi Seb, 
Any news about the release date of 2.1 version?
Thank you

**Comment by sebjulliand** [comment]
Hi Lucia,
it will be June 2024 😉

**Comment by sebjulliand** [comment]
Elias v2.1 is out!
https://github.com/ARCAD-Software/elias-vscode/releases/tag/2.1.0
