### ISSUE TITLE
ARCAD-Observer Codelens issue

### ISSUE THREAD

**Issue by FlorianMartins** [ARCAD-Software/elias-vscode#17]
Hello team !

I hope you doing great !

I have an issue with ARCAD Observer cross references, there is the error message : 

![image](https://github.com/ARCAD-Software/elias-vscode/assets/36245269/80aef679-620d-427f-bc13-b62a26275b1f)

My program don't use this module and it block all the cross reference use...

Do you have an idea about how i can solve it ? 

Thanks you very much for your job !

Best regards,

**Comment by sebjulliand** [comment]
Hello @FlorianMartins !
I do have an idea: upgrade to V2 (unless you have updated already in which case we'll have to dig deeper...).

But v2 was released yesterday, so:
- Update the extension (VSCode should offer it automatically anyway)
- More importantly, update the Elias REST API server. You can grab the new version for the release page here: https://github.com/ARCAD-Software/elias-vscode/releases/latest)

The extension will complain if you run it with a REST server version that is too low anyway.

The v2 server has many bug fixes and especially one that will prevent this kind of crash.

So first update, then let me know how it goes. 😊

**Comment by sebjulliand** [comment]
Elias v2.1 is out!
https://github.com/ARCAD-Software/elias-vscode/releases/tag/2.1.0
