### ISSUE TITLE
Favourite folder doesn't open anymore 

### ISSUE THREAD

**Issue by Vvisscoo** [ARCAD-Software/elias-vscode#19]
👉🏻 Issue text goes here.

When i try to add a version to the favourite's folder it gives me the error below: 

[4/18/2024 10:42:41 AM] [INF] Activating ARCAD Elias
[4/18/2024 10:44:09 AM] [ERR] 404 - Version EUR null 01.05.86 not found in application EUR: {"servlet":"com.arcadsoftware.elias.rest.server.EliasApplication","message":"Version EUR null 01.05.86 not found in application EUR","url":"/elias/arcad/v1/applications/EUR/version/01.05.86","status":"404"}
[4/18/2024 10:45:01 AM] [ERR] 404 - Version EUR null 01.05.86 not found in application EUR: {"servlet":"com.arcadsoftware.elias.rest.server.EliasApplication","message":"Version EUR null 01.05.86 not found in application EUR","url":"/elias/arcad/v1/applications/EUR/version/01.05.86","status":"404"}
[4/18/2024 10:45:14 AM] [ERR] 404 - Version EUR null 01.05.86 not found in application EUR: {"servlet":"com.arcadsoftware.elias.rest.server.EliasApplication","message":"Version EUR null 01.05.86 not found in application EUR","url":"/elias/arcad/v1/applications/EUR/version/01.05.86","status":"404"}

Version 01.05.86 was cancelled, but it seems it keeps looking for it. I've removed the version even from the settings.json file but it didn't fix it. Other than this i'm also not able to even open the favourite's folder.  
<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.9.0|
|Visual Studio Code version|1.88.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
ARCAD-Elias (arcad-elias): 2.0.1
COBOL (cobol): 10.4.11
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.10.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.17.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Debug (ibmidebug): 1.0.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.9.0
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Prettier SQL VSCode (prettier-sql-vscode): 1.6.0
RPGLE (vscode-rpgle): 0.26.4
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID|65535|
|Default CCSID|37|
|SQL|Disabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "ls -p /QIBM/UserData/IBMiDebugService/certs/debug_service.pfx",
    "code": 2,
    "stderr": "/QIBM/UserData/IBMiDebugService/certs/debug_service.pfx not found",
    "cwd": "/home/VSCOLARI"
  },
  {
    "command": "ls -p /QIBM/UserData/IBMiDebugService/certs/debug_service.pfx",
    "code": 2,
    "stderr": "/QIBM/UserData/IBMiDebugService/certs/debug_service.pfx not found",
    "cwd": "/home/VSCOLARI"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"vscolari\" && export HOST=\"DEVELOPM.CUSTOMER.NET\" && export HOME=\"/home/VSCOLARI\" && export WORKDIR=\"/home/VSCOLARI\" && export LIBLS=\"QGPL QRPG <LIBRARY_LIST> QTEMP\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/VSCOLARI"
  }
]
```
</details>

**Comment by sebjulliand** [comment]
Hi @Vvisscoo ,
this is a known problem that happens when a favorited version doesn't exist or has been renamed.

While this is being fixed, you can still manually remove the faulty versions from your user settings.

- Press F1 and select `Open user settings (JSON)`
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/9c58a63b-6e23-4b76-aa76-b5a6b850d16a)
- Search for `favoriteVersions` in the JSON
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/cbda5a23-3cf5-4ff3-af10-fa351c860553)
- Remove the versions that don't exist anymore
- Save the settings

Refresh the Skipper Explorer and the error will be gone.

Hope this helps!

**Comment by Vvisscoo** [comment]
Hello, at first i have removed the version that didn't exist anymore but it kept giving me the same error, so i have removed all the favourite versions and now it is fixed. Thank you.

**Comment by sebjulliand** [comment]
Elias v2.1 is out!
https://github.com/ARCAD-Software/elias-vscode/releases/tag/2.1.0
