### ISSUE TITLE
Missing option for moving component between version VSCode skipper

### ISSUE THREAD

**Issue by petterjohansson** [ARCAD-Software/elias-vscode#2]
![image](https://github.com/ARCAD-Software/elias-vscode/assets/12429224/da9778fb-2dfa-4584-a9d6-6d15533bdfb8)

In RDI you could right-click and move a component from one version to another, can't find the same function in VSCode-Skipper.

**Comment by sebjulliand** [comment]
It's not there yet because calling the "move component" command from VSCode is not possible yet. But we're working on it 😄

**Comment by sebjulliand** [comment]
Hi @petterjohansson ,
the `Move` option has been added in the recently published version 1.5.4:
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/ce0db6de-c1eb-4f6c-b84b-0c482143dfef)
