### ISSUE TITLE
Do not succeed to connect

### ISSUE THREAD

**Issue by ibmiiste** [ARCAD-Software/elias-vscode#20]
Hi, 

I do not succeed to connect. I do not know why.

Regards, 

Olivier.

Find below Vscode's Output:
`--:--:--     0\ncurl: (7) Failed to connect to cica00.ds.ista.com port 9081 after 10 ms: Couldn't connect to server"}
[4/30/2024 2:40:09 PM] [ERR] Can't ping https://cica00.ds.ista.com:9081/elias/arcad/v1
[4/30/2024 2:40:09 PM] [ERR] {"status":-1,"message":"Code: 7\nOutput: \nError: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\ncurl: (7) Failed to connect to cica00.ds.ista.com port 9081 after 10 ms: Couldn't connect to server"}`

And attached, Jetty's log:
[Jetty.log](https://github.com/ARCAD-Software/elias-vscode/files/15164348/Jetty.log)

**Comment by sebjulliand** [comment]
Hello @ibmiiste ,
according to your logs, you try to connect on port 9081 using HTTPS.
Jetty's logs show that it's running on port 9081 for HTTP and 9444 for HTTPS.

In your VSCode settings, you need to either uncheck `Use HTTPS` or change the `Rest API server port` to 9444. Using HTTPS will require you to provide the path to the client certificate.
You also seem to have the `Use SSH` option enabled. Try not to use it unless you must.

Hope this helps!

**Comment by ibmiiste** [comment]
Hi, 

I tried and it seems to be the same:

![image](https://github.com/ARCAD-Software/elias-vscode/assets/13730057/4abe14b3-6444-4dfc-845c-7277447d2287)

Regards, 

Olivier.

**Comment by ibmiiste** [comment]
Hi, 

I Succeed, I used a QSECOFR profil. I think it is too much, what are the necessery privileges to launch JETTY server?

Regards, 

Olivier.

**Comment by sebjulliand** [comment]
Jetty is owned by default by the `JETTY` user that gets created during the installation.
Starting the JETTY server using `STRJTYSVR` submits the command to start Jetty - the submitted job belongs to JETTY so you need to be able to submit a job on behalf of `JETTY` to be able to start it.

**Comment by ibmiiste** [comment]
Thank you, that's why it is running. Great job, thanks!

**Comment by sebjulliand** [comment]
You're very welcome 😄
