### ISSUE TITLE
Continues integration -> edit compile library 

### ISSUE THREAD

**Issue by woutercdinsvest** [ARCAD-Software/elias-vscode#23]
while some other developer is working on a new service program, with procedures that i have to use in my changes, done in an other feature. it is not able to compile. so i have to switch back to RDI because there is an option to edit the library list for compiling.

in RDI you can do this by right click on your feature - properties - library list, then i put the other developers library as second (right after my *verlib

in VS-code i did not yet find a solution for this.

**Comment by sebjulliand** [comment]
The upcoming v2.1 version will allow you to change a Version's library list.
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/457473e7-82d0-486e-b8f4-ec84aabd7ff4)

**Comment by woutercdinsvest** [comment]
what is the estimated release date for V2.1?

**Comment by sebjulliand** [comment]
Elias v2.1 is out!
https://github.com/ARCAD-Software/elias-vscode/releases/tag/2.1.0
