### ISSUE TITLE
All the dates of my program have been changed

### ISSUE THREAD

**Issue by Vvisscoo** [ARCAD-Software/elias-vscode#24]
I was writing some code for my project, when i saved my code, the system has changed every date of the program. For example, one line of code, which date was like 01/01/2024 is now valued as the current date. I've just saved the program, i've not done anything special

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.10.1|
|Visual Studio Code version|1.90.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
.NET Install Tool (vscode-dotnet-runtime): 2.0.6
ARCAD-Elias (arcad-elias): 2.0.1
COBOL (cobol): 10.6.10
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Db2 for IBM i (vscode-db2i): 1.0.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.18.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
Highlight Matching Tag (highlight-matching-tag): 0.11.0
IBM Db2 for z/OS Developer Extension (db2forzosdeveloperextension): 2.1.5
IBM i Debug (ibmidebug): 1.0.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.9.0
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Prettier SQL VSCode (prettier-sql-vscode): 1.6.0
RPG End Code Blocks (rpg-end-code-blocks): 1.0.0
RPGLE (vscode-rpgle): 0.26.6
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID Origin|user|
|Runtime CCSID|65535|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|ILEDITOR.GETMBRINFO|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|||||
|git|setccsid|||||
|grep||||||
|ls||||||
|md5sum||||||
|sort||||||
|stat||||||
|tar||||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF3012:  File FILE_NAME in library *LIBL not found.\nCPC2206:  Ownership of object QZSHSYSTEM in QTEMP type *USRSPC changed.",
    "cwd": "IFS_PATH"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPD0048:  List of values not valid for parameter FILE.\nCPF0001:  Error found on DSPFFD command.\nCPC2206:  Ownership of object QZSHSYSTEM in QTEMP type *USRSPC changed.",
    "cwd": "/IFS_PATH"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"USERNAME\" && export HOST=\"HOST_NAME\" && export HOME=\"/IFS_PATH\" && export WORKDIR=\"/IFS_PATH\" && export LIBLS=\"LIB_LIST" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/IFS_PATH"
  }
]
```
</details>

**Comment by sebjulliand** [comment]
Hi!
You have to turn on Source Date support in your `Code for IBM i` connection settings.
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/a1082bf8-01b9-47be-95d6-5a5f0d7429bf)

See https://codefori.github.io/docs/settings/connection/#enable-source-dates.

**Comment by Vvisscoo** [comment]
> Hi! You have to turn on Source Date support in your `Code for IBM i` connection settings. ![image](https://private-user-images.githubusercontent.com/11096890/339307556-a1082bf8-01b9-47be-95d6-5a5f0d7429bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzE5MjIsIm5iZiI6MTcxODI3MTYyMiwicGF0aCI6Ii8xMTA5Njg5MC8zMzkzMDc1NTYtYTEwODJiZjgtMDFiOS00N2JlLTk1ZDYtNWE1ZjBkNzQyOWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA5NDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMTQzY2YwODE5ZWEzMzM4ODAwYjE5YzZiMWMzNDRlZTVkZDZhOWY3Yjc1OWJkMTgyMDliNmY2ZWM2OTdkYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X1r2-IWukao1Yry0kThzQYhk3YWrD35eJF25s3hXq2o)
> 
> See https://codefori.github.io/docs/settings/connection/#enable-source-dates.

Hello! I have already that option turned on. This has happened multiple times, i have often noticed that this happen when there are some problems with the network, and i imagine vsc takes the system date&time. But this time i had no internet issue.

**Comment by sebjulliand** [comment]
Open an issue for this in [Code for IBM i issue section](https://github.com/codefori/vscode-ibmi/issues) as the member handling is managed by it.
The best course of action is to copy/paste the Code for IBM i output content right after this happens to see if something happened there.

Alternatively, you can try to switch to another source date tracking mode to see if it helps.
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/6576f01b-8e70-42d7-815e-7f47cf5f4cb8)

**Comment by Vvisscoo** [comment]
Ok i will do it. Thank you very much and have a good day!
