### ISSUE TITLE
Server Update via VS Code

### ISSUE THREAD

**Issue by alanashley** [ARCAD-Software/elias-vscode#26]
With the rapid development of the extension, it has the server side restriction messages that client doesn't match server. Would like to have the option to upgrade the elias war file and restart jetty in the process all from the VS Code server admin extension

**Comment by sebjulliand** [comment]
This?
https://arcad-software.github.io/arcad-ibmi-servers/#/pages/jetty_management?id=installupdate-war-files

**Comment by alanashley** [comment]
perfect thanks.

I assume that the restriction of client matching server that both pieces would be available on the repo. Meaning that the extension will always have a compatible server side available.
