### ISSUE TITLE
transfer of one object VS transfer of a version

### ISSUE THREAD

**Issue by dev-wouter** [ARCAD-Software/elias-vscode#27]
hi Seb, 

today i encountered flowing difference between RDI and the VS code plugin

i have a version with a module and the compiled object. and also some other changes.
but i only want to transfer this compiled object to a test device.
-> right click on the object -> transfer to test
![image](https://github.com/ARCAD-Software/elias-vscode/assets/136235433/c88d0f9e-f816-43cb-8944-6abc33c3e729)
this result in a macro running in the background.
and after some time a notification 
![image](https://github.com/ARCAD-Software/elias-vscode/assets/136235433/0d5d2208-0458-4d6f-9e35-03e28a940d68)
BUT 
when i look at the object in greenscreen on the test device, it is not updated (wrkobj)
![image](https://github.com/ARCAD-Software/elias-vscode/assets/136235433/a7ad4ba3-6715-4ad1-b3fb-d185ebc0383d)
![image](https://github.com/ARCAD-Software/elias-vscode/assets/136235433/decd8b58-50b1-48dd-bdbb-085d5ac889db)

when i do the same for that object in RDI 
![image](https://github.com/ARCAD-Software/elias-vscode/assets/136235433/6efb66e8-6513-4865-a30e-d1e854634254)
it does update the creation timestamp
![image](https://github.com/ARCAD-Software/elias-vscode/assets/136235433/345b45e9-fb83-410e-bdf6-e05d158fd004)
and the change date.
![image](https://github.com/ARCAD-Software/elias-vscode/assets/136235433/5847cdc7-940f-4609-9bb4-52e255f14b01)

as far is i can see the macro does the same thing in VS code as in RDI

when transferring the whole version it does update the date and time. but in this case i can't do that, an other object is change in a newer feature witch, and if i transfer this one the whole application ends in error

thanks for looking in to it.

**Comment by sebjulliand** [comment]
Hi @dev-wouter , good catch!
I found the issue and fixed it. I'll ask our QA to validate it and make a release once it's validated.

**Comment by sebjulliand** [comment]
Version 2.1.4 is out and it fixes this issue.
