### ISSUE TITLE
Custom action replacement variable name too long

### ISSUE THREAD

**Issue by SGI495** [ARCAD-Software/elias-vscode#29]
When trying to define a custom version action to execute a macro command and using the suggested replacement variables for `&APPLICATION_CODE`, `&ENVIRONMENT_CODE` and `&VERSION_STATUS`, the REST API responds with a validation error saying that the value for the parameter exceeds 10 characters. 

For example, trying to define this custom version action

```
[
    {
        "name": "Integrate version to I",
        "command": "ARCAD_CUST/INTEGRGRP APP(&APPLICATION_CODE) ENV(&ENVIRONMENT_CODE) VERSION(&VERSION_STATUS) TOENV(I)"
    }
]
```

gives this validation result when trying to save customactions.json

```
[11/07/2024 14:12:03] [ERR] 400 - Bad Request: 

[
    {
        "command": [
            "Value 'APPLICATIO' for APP exceeds 10 characters.",
            "Value 'ENVIRONMEN' for ENV exceeds 10 characters.",
            "Value 'VERSION_ST' for VERSION exceeds 8 characters."
        ]
    }
]
```

There seems to be an issue with the validation being applied on replacement variables as if they where the actual values that will be used when the action is run.

**Comment by sebjulliand** [comment]
Hi @SGI495 ,
grab the elias.war file attached to the latest prerelease: https://github.com/ARCAD-Software/elias-vscode/releases/tag/2.1.2

Use it to update your Elias server and that will fix this issue.
