### ISSUE TITLE
Feature request: Enable editing of additional maintenance reports fields

### ISSUE THREAD

**Issue by SGI495** [ARCAD-Software/elias-vscode#30]
We are using the "Action" field in maintenance reports to describe the solution to a problem, however this field is not editable in the Arcad Elias VSCode interface, so we have to revert to RDi or 5250. The same goes for the "Linked files" tab.

Please make it possible to edit the "Action field" and contents of the "Linked files" tab in VSCode.

**Comment by sebjulliand** [comment]
Version 2.1.7 that was just released adds the Action field to the Maintenance Report editor.
![image](https://github.com/user-attachments/assets/073d0e6f-941d-4180-8f8a-db6cc069eda4)

Support for `Linked Files` will be added in a future major release (tentatively `2.2.0`).

**Comment by sebjulliand** [comment]
Version 2.2.0 is out 🎉
