### ISSUE TITLE
Compare with reference

### ISSUE THREAD

**Issue by dev-wouter** [ARCAD-Software/elias-vscode#32]
Hi, 
this is not rely a issue more an enhancement, but is it possible to do a compare with reference option. in VS code there is only an option to compare with an other version, but reference is not a version.

RDI
![image](https://github.com/user-attachments/assets/e6e69377-1a1e-41dd-b0ba-73fe17949b6f)
VS code
![image](https://github.com/user-attachments/assets/787705a2-fb34-4023-89a3-bbfacb486f67)

thanks

**Comment by sebjulliand** [comment]
The freshly released version `2.1.7` adds the `Compare with reference` action to Components in a version.
![image](https://github.com/user-attachments/assets/898f9c71-ffd2-4e78-bdae-4b9dd34527d7)
