### ISSUE TITLE
Merge and validate only available 1 direction

### ISSUE THREAD

**Issue by RPGLE-Logic** [ARCAD-Software/elias-vscode#33]
Hi there,

We need to be able to merge both ways, from lower versions into higher and vice-versa.

Reason for this is because we need to be able to implement hotfixes on some components.
If someone has PROGRAM1 checked out into version 01.00.01, for a project that'll take a while,
another dev checks out PROGRAM1 into version 01.00.02 and intends to implement ASAP, we need to be able to validate and implement.

**Comment by sebjulliand** [comment]
Hi!
What's preventing you to do so?

**Comment by sebjulliand** [comment]
You can compare a component in a version against any other version by right clicking on the component and selecting `Compare with version...`
![image](https://github.com/user-attachments/assets/c8e5af1c-9ca7-4d28-931e-e2bf296c2bbe)

That will open a side by side comparison editor where changes can be picked with a single click.
