### ISSUE TITLE
Tranfer log missing servername in overview

### ISSUE THREAD

**Issue by dev-wouter** [ARCAD-Software/elias-vscode#34]
hi Seb, 

when displaying the transfer log for an object in a version, you get a nice overview of the transfers, but 1 impotent thing seems to be missing.
![image](https://github.com/user-attachments/assets/818a1961-5696-4b67-b98e-75b8c5dbaa3d)

enhancement -> to what server was de transfer done (we have 3 test servers) 
![image](https://github.com/user-attachments/assets/b7b6117a-abf0-4625-8f35-e316eef3de3c)
in RDI this is the case
![image](https://github.com/user-attachments/assets/d7f4a167-2764-4291-ab8d-56afc4a4f1ea)

thanks for the change

**Comment by dev-wouter** [comment]
hi seb, 

thanks for adding the 'To server' field, but it seems that there is still information missing
![image](https://github.com/user-attachments/assets/cecf38a2-2744-4cf4-b1dd-60fbab65785e)

![image](https://github.com/user-attachments/assets/1d8015e0-eccc-40df-a37c-132a4d94affc)

for example the transfers to a test server are missing in my example

**Comment by sebjulliand** [comment]
Interesting!
Could you run this query and get me the result? (I can't get a suitable test case here).
The filtering may not be ok for components sent to a distant system.
```sql
select * from arcad_prd/aarthstf1 where hst_jobj='you_component' and hst_capp='your_application_code'
```
In particular, the HST_CVER column might be different from the version the component is being modified, which may explain why these lines don't appear.

Thanks!

**Comment by dev-wouter** [comment]
strange enough i don't see the 'To server' in that table. 
 i doe see it when i don't filter on the hst_capp (this seem to be blanks with a integration)

select hst_jsyst, hst_capp from arcad_prd/aarthstf1 
where hst_jobj = 'SMCHGTSHS1' and hst_cver = 'FT.30.03'

![image](https://github.com/user-attachments/assets/e0b016a8-ad89-419c-afa9-b1da3eeb54f3)

**Comment by sebjulliand** [comment]
So it seems that filtering on the application code would hide these lines then.

Before I make a new release, would you find downloading this snapshot and install it to validate that it fixes your issue?
[arcad-elias-2.1.8-SNAPSHOT.vsix.zip](https://github.com/user-attachments/files/16600418/arcad-elias-2.1.8-SNAPSHOT.vsix.zip)

Thanks!

**Comment by dev-wouter** [comment]
it seems ok, only the columns are looking weird now (as the line are in the text)

![image](https://github.com/user-attachments/assets/34b61d7f-aebf-4890-a7a0-ecbadcfc04fc)
