### ISSUE TITLE
Keybind transfer from test, transfer to test and checkin

### ISSUE THREAD

**Issue by benjaminborgen** [ARCAD-Software/elias-vscode#37]
Hi! Is it possible to make these actions available as keybinds for current source under development environment/version/changed?

- Transfer to test
- Retrieve from test
- Checkin

**Comment by sebjulliand** [comment]
Hi @benjaminborgen ,
sure, you can set your own key bindings on any command provided by the extension.

Open the Keybindings editor
![image](https://github.com/user-attachments/assets/fb9b8cfd-ffa8-4fcb-aed3-b5fb7b82059c)


Filter on the commands you want to set a keybinding for and double click on the command to set it.
![image](https://github.com/user-attachments/assets/a8cf274d-ef82-4a80-b899-e72e0720b044)

**Comment by benjaminborgen** [comment]
When I try to execute the command on a source under "Favorite versions" -> Version name -> Changed -> program I get this message.

"Cannot read properties of undefined (reading 'retrieveFromTest')"

![image](https://github.com/user-attachments/assets/e04a9d0a-f2f8-40e4-9f86-0a3e664d7641)

**Comment by sebjulliand** [comment]
Oh, OK, gotcha, that was your main issue all along right? You already had keybindings for those commands but they threw this error, right? That would have been a better way to describe your issue 😉

I'll take note and see what can be done in a future version.

**Comment by benjaminborgen** [comment]
Haha, no... I didn't realize that they were available. 

Thank you! ☺️
