### ISSUE TITLE
working with child versions -> difference RDI / VScode

### ISSUE THREAD

**Issue by dev-wouter** [ARCAD-Software/elias-vscode#38]
hi, 
again an enhancement request,

some team members are willing to switch to VS code, but they are missing the child features overview in VS code.
is there a way to implement this? be aware that the parent version can include open and integrated versions 

![image](https://github.com/user-attachments/assets/a13f2c08-b232-4df9-9688-b9721e020c19)
![image](https://github.com/user-attachments/assets/793a72aa-372a-4424-b49c-3c45ef75d5c2)

**Comment by sebjulliand** [comment]
Yes, this can be implemented in a future version.

**Comment by sebjulliand** [comment]
@dev-wouter  Version `2.2.0` will include a new `Version Tree` node that will allow you to browse the versions hierarchically.
![image](https://github.com/user-attachments/assets/c3979ff5-dabe-44d1-906b-4abda7d4d86d)

**Comment by sebjulliand** [comment]
Version 2.2.0 is out 🎉
