### ISSUE TITLE
Multi-select

### ISSUE THREAD

**Issue by benjaminborgen** [ARCAD-Software/elias-vscode#39]
Hi again! 

When I select members in a version I can only single select. Is it possible to toggle multi-select for transfer- and retrieve from test?

**Comment by sebjulliand** [comment]
In its current state the Skipper Explorer doesn't allow multi-selection.
But I can see into allowing it in a future version.

**Comment by sebjulliand** [comment]
Version 2.2.0 is out 🎉
The explorer now supports multi-selection and keybindings.
