### ISSUE TITLE
Question/Request lock+unlock version

### ISSUE THREAD

**Issue by petterjohansson** [ARCAD-Software/elias-vscode#40]
Is there a lock/unlock version in the Elias extension? 
![image](https://github.com/user-attachments/assets/8d3da8d1-d1b4-4ad5-9cc3-a9e0a9b45159)

If not, that would be something we would need to avoid using RDI. :) 

![image](https://github.com/user-attachments/assets/57f796c5-20da-448b-b700-0646734c0ce4)

Could probably use custom action for now. 

BR,
Petter

**Comment by sebjulliand** [comment]
Hi @petterjohansson ,
I'll add that to my to-do list; it shouldn't be too much trouble to add.

**Comment by sebjulliand** [comment]
Version `2.1.9` is out with this enhancement.
It adds the `Lock` or `Unlock` action depending on the Version's status. The Version item shows a lock icon when the Version is locked.
![image](https://github.com/user-attachments/assets/e470b884-af35-4793-a44d-8c30b01abd61)
![image](https://github.com/user-attachments/assets/3aed3959-1b8a-4904-9864-ca0739a46866)
