### ISSUE TITLE
feature request: properties on an source/object

### ISSUE THREAD

**Issue by dev-wouter** [ARCAD-Software/elias-vscode#42]
in RDI you have a right click properties on a source. 

some team members are using the tab 'Funtional description'
![{CC4CCC03-EEDF-4EE0-92B3-B44090CD530C}](https://github.com/user-attachments/assets/a8a60d29-00fd-47c1-adaf-df1ae36611ca)
or the fields source library/object ref lib in analyses
![{75D8B244-09AE-4675-9764-BC5596CEEFDB}](https://github.com/user-attachments/assets/603d5a31-aad8-4c4b-925a-53b35bf0cbdb)

it seems that you can not find this information in the VS-code plugin

**Comment by sebjulliand** [comment]
Hi @dev-wouter ,
between the issue title and your description, it's a bit confusing to understand what you'd actually like to see added.
Is it the whole Properties dialog that you want or just the Functional description?

As for the source/object ref. library, those are shown in each component's tooltip.
![image](https://github.com/user-attachments/assets/6ac4210a-0bd1-4882-b91b-8709bbd22eba)

**Comment by dev-wouter** [comment]
didn't find the hover tooltip, thanks. 

but it is a bit difficult to use with analyses, so a overview window like property's could be helpful. 
some team members are using the functional description to describe what the program does so if i want them to switch from RDI to VS-code they want to see that. 
for the sourcelib,  object lib, it easier to copy it from a dialog then form the tooltip (its also not copy'able in RDI)

**Comment by sebjulliand** [comment]
An overview window would not fit in VSCode, with regards to VSCode UX guidelines.
However, creating an editor tab that lists a component's properties grouped by tab can be done quite easily.

**Comment by dev-wouter** [comment]
editor tab seems to be ok for what i want.

**Comment by sebjulliand** [comment]
This could be added just in time before the `2.2.0` release planned next week.
There will be a new Properties action in Components' right-click menu:
![image](https://github.com/user-attachments/assets/10058a9e-c99b-43b4-aa09-001e6263d2a4)

It will open an editor with the component's properties and its functional description in a text field.
![image](https://github.com/user-attachments/assets/1700d029-e01e-4f50-8fe8-d92938c1044f)

You'll have to save the editor to save your changes (like a regular editor in VS code).

**Comment by sebjulliand** [comment]
Version 2.2.0 is out 🎉
