### ISSUE TITLE
issue after update code for ibmi

### ISSUE THREAD

**Issue by dev-wouter** [ARCAD-Software/elias-vscode#47]
seb, 

i update the code for ibmi plugin this morning, and tried to open a source in repository but this gives an error. 

error log code for ibmi:
![image](https://github.com/user-attachments/assets/2edd9e15-5d39-4faa-8d14-8cc265d98b5a)
`/home/xxxx: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('CHGJOB CCSID(37)');
CREATE TABLE QTEMP.O_P9FVA AS (SELECT LENGTH(srcdta) as LENGTH FROM ddd.GRDDFT4201_VSCODE_RPGLINT limit 1) WITH DATA;
Call QSYS2.QCMDEXC('CPYTOIMPF FROMFILE(QTEMP/O_P9FVA *FIRST) TOSTMF(''/tmp/vscodetemp-O_ZicwdhM4'') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM('','') DECPNT(*PERIOD)')
{
    "code": 4,
    "signal": null,
    "stdout": "DB2>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.\nDB2>\n\n **** CLI ERROR *****\n         SQLSTATE: 42704\nNATIVE ERROR CODE: -204\nVSCODE in GRDDFT4201 type *FILE not found. \nDB2>\n  ?>\n\n **** CLI ERROR *****\n         SQLSTATE: 38501\nNATIVE ERROR CODE: -443\nCopy command ended because of error.",
    "stderr": ""
}
`
error log arcad elias:
`[10/16/2024 8:35:37 AM] [INF] Activating ARCAD Elias
[10/16/2024 8:38:20 AM] [TRC] Checking ARCAD-Elias REST xxxx@eden token validity
[10/16/2024 8:38:20 AM] [TRC] REST request ARCAD-Elias REST (http) xxxx@eden: get /checkuser  
[10/16/2024 8:38:20 AM] [TRC] REST response ARCAD-Elias REST (http) /checkuser xxxx@eden 200 - OK: {"data":"Hello xxx, you're still connected to eden."}
[10/16/2024 8:38:20 AM] [TRC] Hello xxxx, you're still connected to eden.
[10/16/2024 8:38:20 AM] [TRC] REST request ARCAD-Elias REST (http) xxx@eden: get /applications/aaa/components/SMMVMENTR2/RPGLE/location {"application":"aaa","name":"SMMVMENTR2","type":"RPGLE","version":"24.42.01","fromRepository":true,"readonly":true} 
[10/16/2024 8:38:20 AM] [TRC] REST response ARCAD-Elias REST (http) /applications/aaa/components/SMMVMENTR2/RPGLE/location xxx@eden 200 - OK: {"data":{"file":"QRPGLESRC","library":"GRDPRDS","member":"SMMVMENTR2"}}`

the reason the i put the error here and not in de code for ibmi pluing repo, is that i'm able to open the sources in the code for ibmi plugin.  i will roll back that update on my side so i can work.  

if you need more info just ask
gr wouter

**Comment by sebCIL** [comment]
I have the same problem, with the last update of Code for IBMi v2.13.4

**Comment by sebjulliand** [comment]
Was it OK with `2.13.3` or `2.13.2`? 🤔

**Comment by dev-wouter** [comment]
those doe not excist , i update from 2.13.0 to 2.13.4
but yeterday it worked

**Comment by sebCIL** [comment]
It's OK with v2.13.0.

I don't kwow how to install v2.13.3 :
![image](https://github.com/user-attachments/assets/f9202ecb-bae0-4956-8188-ee9f91af4b30)

**Comment by sebjulliand** [comment]
Thanks for the quick reply, both of you 😅
If you click on `Switch to pre-release`, then the pre-release versions become available for you to install:
![image](https://github.com/user-attachments/assets/68a1ec40-71cf-4c91-a1e5-c151b8349052)

Are your members in ARCAD located on an iasp? (@sebCIL looks like your `DENITRAL` application is).

**Comment by dev-wouter** [comment]
seb, i dont see the option to have any pre-release versions
![image](https://github.com/user-attachments/assets/524698ab-5645-4e7e-b6d7-304d926d4a91)
or i'm i missing something?

**Comment by dev-wouter** [comment]
found the older version
https://marketplace.visualstudio.com/items?itemName=HalcyonTechLtd.code-for-ibmi&ssr=false#version-history 
 
already tested  2.13.3 <- same issue as current

**Comment by dev-wouter** [comment]
issue seems to have occurs after the 2.13.1 update.
so in the change of 2.13.2

**Comment by sebjulliand** [comment]
The same kind of problem has been reported on the Code for i repository: https://github.com/codefori/vscode-ibmi/issues/2289
I made a fix, but it needs to be validated before being released. At least we're moving in the right direction.

In the meantime, I built the vsix with the fix for you to test, if you want to check if that works for you:
[code-for-ibmi-2.13.4-dev.0.vsix.zip](https://github.com/user-attachments/files/17408062/code-for-ibmi-2.13.4-dev.0.vsix.zip)

Download the zip, get the vsix in it and install it in VS Code.
![image](https://github.com/user-attachments/assets/13ff5ce8-07c2-4ed2-bd67-44a41558c3e6)

Hopefully that will take care of this issue. Thanks for any feedback!

**Comment by sebCIL** [comment]
Hi,

Sorry, always the same problem:
![image](https://github.com/user-attachments/assets/3ddd5ae3-8ce7-40bb-837e-7a4dba177488)

![image](https://github.com/user-attachments/assets/5dd6f859-dbcd-4b2d-a9aa-b6526f34ccc8)

**Comment by sebjulliand** [comment]
Can you paste here the Code for IBM i output please?

**Comment by sebCIL** [comment]
```
/home/BOURREAU: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
CREATE OR REPLACE ALIAS ILEDITOR.DENDSB0002_QRPGLESRC_DEN0322 for "DENDSB0002"."QRPGLESRC"("DEN0322")
/home/BOURREAU: /usr/bin/attr -p /QSYS.LIB/DENDSB0002.LIB/QRPGLESRC.FILE/DEN0322.MBR CREATE_TIME MODIFY_TIME DATA_SIZE
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "attr: 001-2248 Error found getting attributes for file /QSYS.LIB/DENDSB0002.LIB/QRPGLESRC.FILE/DEN0322.MBR.  No such path or directory."
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.",
    "stderr": ""
}

/home/BOURREAU: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
CREATE TABLE QTEMP.O_WSGHN AS (select srcdat, rtrim(translate(srcdta, x'2F', x'25')) as srcdta from ILEDITOR.DENDSB0002_QRPGLESRC_DEN0322) WITH DATA;
Call QSYS2.QCMDEXC('CPYTOIMPF FROMFILE(QTEMP/O_WSGHN *FIRST) TOSTMF(''/home/BOURREAU/.vscode/vscodetemp-O_NILb8oMf'') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM('','') DECPNT(*PERIOD)')
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.\nDB2>\n  ?>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.",
    "stderr": ""
}

/home/BOURREAU: rm -rf "/home/BOURREAU/.vscode/vscodetemp-O_NILb8oMf"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}
```

**Comment by sebCIL** [comment]
**Nota:** 
with the new version v2.13.4-dev.0, I can't, directly, open a source with CTRL+ALT+P
![image](https://github.com/user-attachments/assets/8345ccd1-50a1-4f97-b0e9-05fa8aeaee74)

**Comment by sebjulliand** [comment]
Something's missing from the output...it must retry to locate the member if not found on sysbas, looping through all available iasps.
Can you try to reconnect and reload settings on your system, try to open a member again, and if it fails, send the Code for i output from the start.
![image](https://github.com/user-attachments/assets/33ef6aa0-4d26-478e-bcdc-c3a64fca0682)

**Comment by sebjulliand** [comment]
The fix was validated a minute a go and merged into the master branch.
I'm published a new 2.13.5 release, it should show up in VS Code in a few minutes. After you upgraded to 2.13.5, you'll be able to open members (and Skipper Components) located on iasp (it worked for me on an application hosted on an iasp).

Let me know how it goes once 2.13.5 is installed.

**Comment by sebCIL** [comment]
OK, I'll test it as soon as I can.
I'll keep you posted

**Comment by sebjulliand** [comment]
It says "restart extensions"...Can you restart VS Code and try again? (sorry, can't figure out why it doesn't go through your iasps...)

**Comment by sebCIL** [comment]
oops, I forgot to do it 😅
Right away, it works better !

I can open sources member.

I'm still checking...

**Comment by sebjulliand** [comment]
Hi @sebCIL @dev-wouter , how is it going? Can we close this issue?

**Comment by sebCIL** [comment]
Yes, it works fine, you can close it.

**Comment by sebjulliand** [comment]
Thanks!
