### ISSUE TITLE
Component with special characters

### ISSUE THREAD

**Issue by sebCIL** [ARCAD-Software/elias-vscode#48]
I try to create a new component with special characters 'à' but an error message appear:
![image](https://github.com/user-attachments/assets/c6521b38-1579-4d19-b645-e6d3208815b0)

The first thing is that i entry an 'à' and it change it to 'À'.

elias.log :
```
2024-10-16 09:22:23,391 [qtp1036667778-375] ERROR com.arcadsoftware.elias.rest.server.authentication.service.ArcadConnectionService [] - Error during *LIBL/AADDSRCARC OBJLIBTYPE() SRCFILE(RTNDSB0001/QRPGLESRC) SRCLIBTYPE(*L01) CRTTYPE() SRCMBR(ÀRTVOBJCLP) ENV('ROUTINES' 'D' 'SB.00.01') TYPE(RPGLEINC) execution:
	[CPD0078] [30] La valeur 'ÀRTVOBJCLP' du paramètre SRCMBR n'est pas un nom correct.
	[CPF0001] [30] Erreur trouvée dans la commande AADDSRCARC.

```

No problem with the RDi's plugin.

**There's no urgency.**

**Comment by sebjulliand** [comment]
Argh, there must be one or more places in the code where the component's name gets uppercased and it doesn't go well when using CCSID 297 or 1147, since `à` is one of the variant characters for these CCSID (who doesn't love CCSID issues? 😅).

This should be an easy fix, hopefully.

**Comment by sebjulliand** [comment]
Hello @sebCIL , are you still having issues or can this be closed?

**Comment by sebCIL** [comment]
Sorry, I didn't know it had been fixed.
It works fine, you can close it.

**Comment by sebjulliand** [comment]
No worries, @sebCIL the issue was on Code for i side 😉
