### ISSUE TITLE
RFE : search box for versions

### ISSUE THREAD

**Issue by petterjohansson** [ARCAD-Software/elias-vscode#7]
![image](https://github.com/ARCAD-Software/elias-vscode/assets/12429224/f15ba34b-f9e7-44fd-ab8b-0cd79cad152a)

Request for enhancement. Just like repository have search capabilities, we would like that you could search and filter the same way within a version.

**Comment by petterjohansson** [comment]
Hi @sebjulliand!

This looks great. 👍

**Comment by sebjulliand** [comment]
Perfect! This will be released soon (v2, a major update) 👍🏻

**Comment by sebjulliand** [comment]
This can be closed, version 2 is now out! Make sure to update bother the REST Server and the extension (the extension will check the REST Server version anyway).
