### ISSUE TITLE
RFE: change type (RPGLE -> SQLRPGLE)

### ISSUE THREAD

**Issue by petterjohansson** [ARCAD-Software/elias-vscode#8]
Missing action to change source type:
![image](https://github.com/ARCAD-Software/elias-vscode/assets/12429224/47ec3314-f243-4755-a003-a48366f838c2)

**Comment by sebjulliand** [comment]
Hi @petterjohansson ,
the Type change will be available with Elias version 2.1.
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/c99c9318-e348-4ba8-a2f1-1bc3f6512fdb)

**Comment by sebjulliand** [comment]
Elias v2.1 is out!
https://github.com/ARCAD-Software/elias-vscode/releases/tag/2.1.0
